
export const DataTallas = [
  {key: '4', name:'4'},
  {key: '6', name: '6'},
  {key: '8', name: '8'},
  {key: '10', name: '10'},
  {key: '10.5', name: '10.5'},
  {key: '11', name: '11'},
  {key: '11.5', name: '11.5'},
  {key: '12', name: '12'},
  {key: '12.5', name:'12.5'},
  {key: '13', name:'13'},
  {key: '13.5', name:'13.5'},
  {key: '14', name:'14'},
  {key: '16', name:'16'},
  {key: 'XS', name:'XS'},
  {key: 'S', name:'S'},
  {key: 'M', name:'M'},
  {key: 'L', name:'L'},
  {key: 'XL', name:'XL'},
  {key: 'XXL', name:'XXL'},
  {key: 'XXXL', name:'XXXL'},
  {key: 'No aplica', name:'No Aplica'},
]